name: Auto Build Blog and Push

on:
  push:
    branches: [main]

jobs:
  build-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # adjust if needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Auto: update index.html [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
